version: "3.8"

services:
  vite-app:
    build: .
    ports:
      - "8000:80"  # Expose port 8000 for the Vite app
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}   # You can replace with your environment variables
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}  # Replace with your actual environment variable names
    env_file:
      - .env  # Optional: You can put your env variables in a `.env` file